name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Africa/Algiers
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_stars: yes
          plugin_streak: yes
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator, organization_member
